from enum import IntEnum

class Properties(IntEnum):
    UNKNOWN = 0
    AIR_TEMPERATURE = 1
    ALKALINITY = 2
    AMMONIA_NITROGEN = 3
    CHLOROPHYLL = 4
    CONDUCTIVITY = 5
    DISSOLVED_OXYGEN = 6
    E_COLI = 7
    ENTEROCOCCUS = 8
    NITRATE_NITROGEN = 9
    ORTHOPHOSPHATE = 10
    PH = 11
    PHOSPHORUS = 12
    SALINITY = 13
    TOTAL_DEPTH = 14
    TOTAL_DISSOLVED_SOLIDS = 15
    TOTAL_NITROGEN = 16
    TOTAL_SUSPENDED_SOLIDS = 17
    TURBIDITY = 18
    WATER_TEMPERATURE  = 19