name: hackthebay
channels:
  - defaults
dependencies:
  - attrs=19.3.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cffi=1.14.0
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - curl=7.67.0
  - dash=1.4.1
  - dash-core-components=1.3.1
  - dash-html-components=1.0.1
  - dash-renderer=1.1.2
  - dash-table=4.4.1
  - descartes=1.1.0
  - expat=2.2.9
  - fiona=1.8.13.post1
  - flask=1.1.2
  - flask-compress=1.5.0
  - freetype=2.10.2
  - freexl=1.0.5
  - future=0.18.2
  - gdal=3.0.2
  - geopandas=0.8.1
  - geos=3.8.0
  - geotiff=1.5.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - intel-openmp=2020.1
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - jpeg=9b
  - kealib=1.4.7
  - kiwisolver=1.2.0
  - krb5=1.16.4
  - libboost=1.67.0
  - libcurl=7.67.0
  - libgdal=3.0.2
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.2
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxml2=2.9.10
  - lz4-c=1.8.1.2
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - markupsafe=1.1.1
  - matplotlib-base=3.2.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - numpy=1.19.1
  - numpy-base=1.19.1
  - openjpeg=2.3.0
  - openssl=1.1.1g
  - pandas=1.0.5
  - pcre=8.44
  - pip=20.2.2
  - postgresql=11.2
  - proj=6.2.1
  - pycparser=2.20
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyqt=5.9.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - retrying=1.3.3
  - rtree=0.9.4
  - setuptools=49.6.0
  - shapely=1.7.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.32.3
  - tbb=2018.0.5
  - tiledb=1.6.3
  - tk=8.6.10
  - tornado=6.0.4
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wincertstore=0.2
  - xerces-c=3.2.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - autopep8==1.5.4
    - cycler==0.10.0
    - matplotlib==3.3.0
    - pillow==7.2.0
    - plotly==4.9.0
    - pycodestyle==2.6.0
    - toml==0.10.1